version: "3.9"
services:
  backend:
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/src
    ports:
    - '18000:8000'
    environment:
      DEBUG: "True"
      SECRET_KEY: django-insecure-@w6%i*cfvma^%o$q8k)_vql*bip(e0bjlw%#$zpjji%59rj6x!
      POSTGRES_NAME: online_shop
      POSTGRES_USER: online_shop
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      STATIC_ROOT_RELATIVE: public/static/
      STATIC_URL: /static/
      MEDIA_ROOT_RELATIVE: public/media/
      MEDIA_URL: /media/
    depends_on:
      - db

  db:
    image: postgres
    ports:
    - '15432:5432'
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: online_shop
      POSTGRES_USER: online_shop
      POSTGRES_PASSWORD: postgres_password
      PGDATA: /tmp
    restart: always
