services:
  backend:
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/src
    ports:
    - '8000:8000'
    environment:
      - POSTGRES_NAME=online_shop # Probably it's DB name
      - POSTGRES_USER=online_shop
      - POSTGRES_PASSWORD=postgres_password
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=online_shop
      - POSTGRES_USER=online_shop
      - POSTGRES_PASSWORD=postgres_password
